server:
  port: 18084
spring:
  application:
    name: sentinel-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      scg.fallback:
        mode: response
        response-status: 444
        response-body: 1234
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: test_route
          uri: lb://sentinel-gateway-service
          predicates:
            - Path=/test/**